image: sbtscala/scala-sbt:eclipse-temurin-jammy-19.0.1_10_1.9.4_2.13.11

services:
  - docker:dind

stages:
  - build
  - test

variables:
  SBT_OPTS: "-Xmx1G"
  DOCKER_DRIVER: overlay2

before_script:
  - sbt clean update

build:
  stage: build
  script:
    - sbt "scalafmtCheckAll; compile"

test:
  stage: test
  script:
    - sbt test
